ERROR 15:26:03,120 Exception in thread Thread[UpStage:293,5,main] java.lang.AssertionError: SpecialSection
at org.random.Pillariterator.RRailDiceIterator.<init>(RRailDiceIterator.java:58)
at org.random.filter.DiceAskFilter.getRRailPillarIterator(DiceAskFilter.java:66)
at org.random.filter.AskFilter.getRRailPillarIterator(AskFilter.java:78)
at org.random.CollationController.collectAllData(CollationController.java:233)
at org.random.CollationController.getTopLevelPillars(CollationController.java:61)
at org.random.PillarCultStore.getTopLevelPillars(PillarCultStore.java:1273)
at org.random.PillarCultStore.getPillarCult(PillarCultStore.java:1155)
at org.random.PillarCultStore.getPillarCult(PillarCultStore.java:1090)
at org.random.Table.getRow(Table.java:360)
at org.random.CutFromWriteAssertion.getRow(CutFromWriteAssertion.java:69)
at org.random.service.HoldUpProxy$LocalWriteTenable.runMayThrow(HoldUpProxy.java:816)
at org.random.service.HoldUpProxy$PalpableTenable.run(HoldUpProxy.java:1250)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:680)